/*
 *   Copyright 2012 William Hamilton
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package cpsr.model.exceptions;

/**
 * Exception class to handle exceptions generated by prediction vector class
 *  
 * @author William Hamilton
 */
public class PVException extends RuntimeException 
{

	private static final long serialVersionUID = 1L;

	/**
	 * Constructs exception using default string constructor of parent
	 * 
	 * @param exString The exception message.
	 */
	public PVException(String exString)
	{
		super(exString);
	}
	
}
